### ISSUE TITLE
Update the Kotlin version

### ISSUE THREAD

**Issue by MickaelHrndz** [flowmobile/storage_space#5]
Hello,

I wanted to use this package in a recently created Flutter project but I'm not able to run it :

> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> project ':storage_space' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by OVargas96** [comment]
Hi! I have the same problem, were you able to solve it?
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':storage_space' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50`

**Comment by oodavid** [comment]
Fixed by latest release
